"""init tables

Revision ID: cc23fe604226
Revises: 
Create Date: 2026-01-28 18:24:14.910940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc23fe604226'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income_ttm', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_stats_industry'), 'symbol_stats', ['industry'], unique=False)
    op.create_index(op.f('ix_symbol_stats_symbol'), 'symbol_stats', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_stats_symbol'), table_name='symbol_stats')
    op.drop_index(op.f('ix_symbol_stats_industry'), table_name='symbol_stats')
    op.drop_table('symbol_stats')
    # ### end Alembic commands ###
