"""add symbol_industries

Revision ID: f0dc6f0d69ca
Revises: cc23fe604226
Create Date: 2026-01-28 18:27:57.767536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dc6f0d69ca'
down_revision: Union[str, Sequence[str], None] = 'cc23fe604226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_symbol')
    )
    op.create_index(op.f('ix_symbol_industries_industry'), 'symbol_industries', ['industry'], unique=False)
    op.create_index(op.f('ix_symbol_industries_symbol'), 'symbol_industries', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_industries_symbol'), table_name='symbol_industries')
    op.drop_index(op.f('ix_symbol_industries_industry'), table_name='symbol_industries')
    op.drop_table('symbol_industries')
    # ### end Alembic commands ###
