"""add price column and industry aggregates table

Revision ID: fe4855caf07b
Revises: f0dc6f0d69ca
Create Date: 2026-01-28 21:44:47.440696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4855caf07b'
down_revision: Union[str, Sequence[str], None] = 'f0dc6f0d69ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('avg_pe_ratio', sa.Float(), nullable=True),
    sa.Column('avg_revenue_growth', sa.Float(), nullable=True),
    sa.Column('sum_revenue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry')
    )
    op.add_column('symbol_stats', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbol_stats', 'price')
    op.drop_table('industry_aggregates')
    # ### end Alembic commands ###
